[package]
name = "sheet-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.24.0"
crossterm = "0.27.0"
calamine = "0.22.1"
anyhow = "1.0.79"
clap = { version = "4.5.0", features = ["derive"] }
rust_xlsxwriter = "0.86.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
indexmap = { version = "2.0", features = ["serde"] }
ratatui-textarea = "0.4.0"
